### ISSUE TITLE
Fix API Logging Script

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/tools#102]
The logging is not working.

**Comment by phillip-hopper** [comment]
@jag3773, I'm not sure which script this issue is referring to.

**Comment by jag3773** [comment]
https://github.com/unfoldingWord-dev/tools/blob/master/uw/log_to_ga.py

**Comment by phillip-hopper** [comment]
@jag3773, it seems that it isn't writing to the log because it isn't running. It wrote when I started it from the command line. However, it seems when it does run, the script is failing for a reason I haven't found yet.

**Comment by phillip-hopper** [comment]
@jag3773: Is this still a problem?

**Comment by jag3773** [comment]
Yes, the data I see is 1 hit every few days, which cannot be correct.

Thank you,
Jesse Griffin
unfoldingWord Chief Technology Officer

**Comment by jag3773** [comment]
This issue was moved to unfoldingWord-dev/Door43#285
