### ISSUE TITLE
Publish tW to uW Catalog

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/tools#104]
We need to publish translationWords as a standalone project to the uW catalog.

**Comment by richmahn** [comment]
So what are the steps for this to be done/successful? We need to add info to the catalog.json file I assume for the location of the file, and then have a location of the file. I need more info on how to modify the catalog.json file and where files like this should go.

**Comment by jag3773** [comment]
This issue was moved to unfoldingWord-dev/translationDatabaseWeb#146
