### ISSUE TITLE
Include Page number in term link

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/tools#105]
Currently, the PDF links to key terms, which is ideal for computer use.  However, we plan to print some of these as well, so it would be great if we could include the page number that the term shows up on in addition to the link.

**Comment by richmahn** [comment]
Should be possible since it links to the page. Will have to learn how to know what page it links to and print it. However, this all comes from the HTML file when generated by pandoc to a PDF, so may be difficult.

**Comment by jag3773** [comment]
This issue was moved to unfoldingWord-dev/Door43#283
