### ISSUE TITLE
tW Standalone PDF

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/tools#108]
Can we get a variant PDF that is *only* translationWords and all of them?

**Comment by richmahn** [comment]
Yes, would have to start from a page that lists all of them and go from there.

**Comment by jag3773** [comment]
https://door43.org/en/obe/home

Thank you,
Jesse Griffin
unfoldingWord Chief Technology Officer

**Comment by jag3773** [comment]
Note that you'll only want to pull in pages that have the "publish" tag on them.

**Comment by richmahn** [comment]
Jesse, just a note to make sure it is ok, I don't pull that URL you gave me since we should only use terms that are published, so I just grep the en/obe/kt/* for ones with tag>publish and then get their html. Then I do the en/obe/other/* files. Should I kept them as two different sections (Key Terms and Other Terms) like the website, or should they all be lumped together in the listing and page order?

**Comment by richmahn** [comment]
Also, what should I do about linking Bible verses at the end of each term? Link to website? Remove link? Pull in the text and have a Bible reference section with all Bible references?

**Comment by ChrisJarka** [comment]
It would be good to have the references there for the information - since there most likely will not be internet - having the references listed without links would be good.

**Comment by richmahn** [comment]
@jag3773 @ChrisJarka Hmm, so I could follow the link to the tN page, but I assume we don't want th whole tN page as there are a bunch of links and references there. Should I extract the Bible verse there? Or is there a better way (API) to get a Bible verse? What Bible version should I use?

**Comment by richmahn** [comment]
What I mean above ^^^, I mean have the script follow the link and get that HTML page

**Comment by ChrisJarka** [comment]
![transgress](https://cloud.githubusercontent.com/assets/9850185/8997947/6279ade0-36f5-11e5-91a3-6dca1aa42b90.png) Here are the links at the bottom of the Transgress term page. The links go to chunk/Bible passages that has that word in the ULB. If you extract the Bible verse - it should be the ULB. Wouldn't the entire chunk of the ULB be extracted from that reference page? I think for the purpose of the PDF (especially with a stand-alone book) that a list of the possible places that the term is used in the Bible would be fine. (no linking or extracting)

**Comment by jag3773** [comment]
This issue was moved to unfoldingWord-dev/Door43#281
