### ISSUE TITLE
tN OBS Standalone PDF

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/tools#111]
We need a modification of the tN PDFs to use for OBS.  This should be a matter of reading the content from the catalog and generating the PDF accordingly.

https://api.unfoldingword.org/obs/txt/1/en/obs-en.json
https://api.unfoldingword.org/obs/txt/1/en/tN-en.json
https://api.unfoldingword.org/obs/txt/1/en/kt-en.json
https://api.unfoldingword.org/obs/txt/1/en/CQ-en.json

We need an example for feedback by the 7th.  Please post to #resources channel and have Christine review.

**Comment by phillip-hopper** [comment]
From @timjore: I wonder if it would help to have a link back to the table of contents in the header of every page of the exported PDFs. That will make it easy, no matter how many clicks a translator is into the work (key terms, questions, etc.) to get back to the TOC.

**Comment by phillip-hopper** [comment]
@richmahn, I'm passing this back to you now. The work I've done is here: https://github.com/phillip-hopper/tools/commit/e4298c8d0a692f9b014ee5beccbd4ae9ec77f978

**Comment by jag3773** [comment]
This issue was moved to unfoldingWord-dev/Door43#279
