### ISSUE TITLE
Import PBT Material to ULB etherpad

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/tools#114]
The PBT introductory material needs to be imported into the ULB in etherpad, utilizing the 00 chapter for each book (e.g. /p/en-ulb-rom-00).

**Comment by phillip-hopper** [comment]
@jag3773, pretend I don't know what PBT stands for. :blush:

**Comment by jag3773** [comment]
There is a zip file of these resources, Christine or Larry may know where
they are, please ask them on the #resources channel.

Thank you,
Jesse Griffin
unfoldingWord Chief Technology Officer

**Comment by phillip-hopper** [comment]
@jag3773, the etherpad pages appear to be in USFM format. What format should I use for the introductory material?

**Comment by jag3773** [comment]
What is the source formatted as?  I think we want USFM.  We are talking about a paragraph or so, right?

**Comment by jag3773** [comment]
This issue was moved to unfoldingWord-dev/Door43#276
