### ISSUE TITLE
OBS PDF Font Tex File

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/tools#125]
Currently, the obs/book/pdf_export.sh script requires that there be a obs/tex/noto-[langcode].tex file or the script will fail.

Either this dependency needs removed, or the pdf_export.sh script should create a default one for new languages.

**Comment by alerque** [comment]
Hmm. My recollection is that there was a map somewhere of languages to tex includes, but I was a little confused by the existing setup and left that part most untouched. I'll look into this, but it won't be until probably Saturday that I can get to it. Is this what was killing the Farsi build?

**Comment by jag3773** [comment]
No, appears to be a different issue for the Farsi build.

Thank you,
Jesse Griffin
unfoldingWord Chief Technology Officer

**Comment by jag3773** [comment]
Actually, that was the problem for Farsi, I'm building it now.  There is a different error for the sgj language, unfoldingWord-dev/Door43#245.

**Comment by alerque** [comment]
As much for my own sake as anything else, the link to the Farsi issue report is unfoldingWord-dev/Door43#152.

**Comment by alerque** [comment]
So the problem with Farsi is that Noto is broken. I may have a workaround posted shortly but I'm going to get kicked out of the building in 15 min so if I don't make it it will be tomorrow. I do have a working FA build I just have to fix the code properly. Just so you all know, problem found.

**Comment by alerque** [comment]
I'm going to have to split, but the basic font problem and most of the directional issues are fixed on my end. There are some nagging ligature issues as well as quite a few document alignment issues where somebody hard coded directions instead of using language direction offsets, but I'll clean up my commits and send them over.

**Comment by alerque** [comment]
This is … way more of a pain in the neck than one would think!

In actuality the whole way the languages are specified in the ConTeXt template is just screwy. Even worse, doing it right isn't going to be a walk in the park. Some languages are going to be a pretty cookie cutter affair, but some have extra typesetting considerations to be setup. Some of these "extra considerations" don't follow the same patterns as others, e.g. code needs to be injected in different orders.

The work I'm doing to enable Farsi in unfoldingWord-dev/Door43/#152 should mostly cover this, and there will just be a few things to touch up on top of that to make adding new languages a bit simpler than digging through ConTeXt source code.
