### ISSUE TITLE
Final chunk of chunks.json has incorrect id

### ISSUE THREAD

**Issue by PurpleGuitar** [unfoldingWord-dev/tools#150]
In each chunks.json file, the final chunk has an incorrect ID.  For example:

https://api.unfoldingword.org/ts/txt/2/1ch/en/ulb/chunks.json

The final chunk should have an id of "29-29" (Chapter 29, chunk 29), but instead has an id of "29-00".

Every chunks.json file I inspected has the same issue.

**Comment by jag3773** [comment]
Just a note that the fix for this is actually in https://github.com/unfoldingWord-dev/tools/commit/3ba8da69fd75969ad8f7dc77a376ce92a2e51e3a.  But we can't deploy this change until we move into a v3 for the api.
