### ISSUE TITLE
Script to Move Etherpad Bible Texts to Github

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/tools#161]
We need a script that exports the ULB and UDB pages from etherpad and puts them into a directory that can be pushed up to github.

The github repos are: https://github.com/Door43/ulb-en and https://github.com/Door43/udb-en.  See Google Doc for more notes.

Note that the script does not have to do the git stuff, just dump them into a directory and then commit and push on the cli.

Two stages here:

1. Copy everything over immediately so that people can check it out and learn how Github works.
2. Halt the text team and do the copy to Github, then disable the etherpad pages.

**Comment by richmahn** [comment]
script for  this is tools/uwb/ep_export_by_chapter.py
