### ISSUE TITLE
Can We Split Chunk Markers Mid-Verse

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/tools#164]
There are a few places where the text team would like to split a verse between two chunks, the spots are:

* Gen 35:22-23
* 2Sa 19:8-9
* Neh 7:7-8

We need to:

* [ ] Review those locations in the current chunks to see if there are problems (chunks.json and tS)
* [ ] Determine if we want to support mid-verse splits, if yes, rewrite the chunk making code

Some things to consider if we support mid-verse chunking:

* Importing USFM texts from outside our ecosystem will become much more difficult, a human would have to set the marker in the appropriate location
* We would need to rewrite our chunk publishing/making tools
* We would need to verify that these changes don't cause problems in tS or Door43 (anywhere else)?

**Comment by klappy** [comment]
I can definitely see how this can raise issues and concerns from a technical perspective. 
Where possible, making certain tags/containers nest-able is ideal. Splitting them will cause us to have to rethink data structures that are not usfm.

**Comment by jag3773** [comment]
Issue moved to [unfoldingWord-dev/door43.org #109](https://github.com/unfoldingWord-dev/door43.org/issues/109) via [**ZenHub**](https://www.zenhub.com/)
