### ISSUE TITLE
Start Including Chunk Zero Pages in tN

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/tools#166]
Each book and each chapter in Door43 is getting "chunk zero" pages that provide introductory information to the book or chapter.  We need to start including these as we publish tN and then signal tS to include this data in the resources pane.

**Comment by neutrinog** [comment]
@jag3773 we cannot do this until we fix the bug where the last chunk in a chapter has an id of 0. And we decided it was not safe to do that unless we bumped the api version.

**Comment by jag3773** [comment]
@neutrinog OK!  Funny how that keeps coming back!  Hopefully next week we'll make some serious progress on the new API with @phillip-hopper.

**Comment by jag3773** [comment]
Book intro: https://door43.org/en/bible/notes/mat/00/intro
Chapter intro: https://door43.org/en/bible/notes/mat/01/00

**Comment by jag3773** [comment]
Make sure to key off the "publish" tag for these.

**Comment by richmahn** [comment]
@jag3773 I don't understand your last comment, especially in the light of the #167 ...should we still be looking at a publish tag?

**Comment by richmahn** [comment]
And should I bump up the API directory to v3 for this?

**Comment by jag3773** [comment]
Issue moved to [unfoldingWord-dev/door43.org #118](https://github.com/unfoldingWord-dev/door43.org/issues/118) via [**ZenHub**](https://www.zenhub.com/)
