### ISSUE TITLE
tA Conversion Script

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/tools#170]
We need a script that can take tA from it's current etherpad form and transform it in the following ways:

 - [x] Convert DW to Markdown
 - [x] Split each **manual** out to it's own directory (probably `ta-audio` as an example)
 - [x] Convert all links to be absolute URLs, using https://git.door43.org/Door43/[manual] as the base (e.g. follow pattern above)

Each directory should then be committed to it's own repo in Gogs Door43 org (https://git.door43.org/Door43).

We also need to account for moving the discussion/comment threads over into the repos somehow.  For example, thread at the bottom of https://door43.org/en/ta/workbench/translate/active needs migrated.  Can we tie an issue to a particular file in the repo with a link somehow?

**Comment by jag3773** [comment]
Here is a list of all the repos that should be created in the Door43 organization:

- en-ta-intro
- en-ta-process
- en-ta-gl
- en-ta-audio
- en-ta-translation-vol1
- en-ta-translation-vol2
- en-ta-checking-vol1
- en-ta-checking-vol2

**Comment by jag3773** [comment]
@richmahn each repo should be structured like this:
```
repo/
    |-LICENSE.md
    |-CONTRIBUTORS.md
    |-content/
        |-toc.yml
        |-module_name.md
        ...
```

**Comment by richmahn** [comment]
@jag3773: I know not needed right away, but where does the content of CONTRIBUTORS.md come from? Just start with a blank file and let people add their name like with ULB/UDB, or, in generating these module.md files, look at the credit: field and add any names to the CONTRIBUTORS.md file? (so far haven't seen names in the files on epad I looked at) I already loop through the epad ta pages for other data, so wondering if you want me to build this file or not.

**Comment by jag3773** [comment]
You can just put the intro from https://github.com/Door43/ulb-en/blob/master/CONTRIBUTORS.md into these CONTRIBUTORS.md.  The `credits` field is to attribute sources that were referenced in writing the article, we do *not* want to use that in the CONTRIBUTORS.md file.

**Comment by ChrisJarka** [comment]
Are you migrating the workbench namespace also? I didn't think so. All volumes made from the ether pad do not have discussion panels.
