### ISSUE TITLE
Reveal Notes UI

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/tools#21]
Let's use a white arrow on the right of the screen to indicate the notes, similar to the arrow on the left that indicates the menu.

**Comment by phillip-hopper** [comment]
All updated files are in the unfoldingWord repository, rather than this one.

**Comment by jag3773** [comment]
Looks good but I think the arrow should be centered, like it is on the left (see https://unfoldingword.org/en/360px/01/#/1).

**Comment by neutrinog** [comment]
hey guys, just saw in the above link that if you click on the arrow to navigate to the next frame it breaks the scrolling in the left library list.

**Comment by phillip-hopper** [comment]
@neutrinog, is the bug you reported above still happening? If it is, please give specifics on how to reproduce it. All the scrolling seems to be working fine in Chrome on Windows 7.

**Comment by neutrinog** [comment]
@phillip-hopper I don't remember where the link to the page is. Could you send send that to me?

**Comment by phillip-hopper** [comment]
Updated uw.css so the arrow is centered vertically.
