### ISSUE TITLE
Graphviz and Page Copy

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/tools#34]
objectives:
 
create all content in tA in a structured format that defines:
* title of the module
* location of the module on Door43
* dependencies of the module on other modules

use this information to programmatically render the content:
* in the correct location on Door43
* as a dependency map showing the relationship between all modules
  * the map should include one subgraph for all modules in volume “vol1"
  * the nodes of the map should be color-coded by section

implementation:

* create a root page in Pad with links to all tA modules (also in Pad)
* collaboratively build all modules in Pad
* use a YAML header on each module to declare the meta information

YAML meta information key:

* title: This is the title of the module (note: should be used as the page name on tA and the module name on the concept map)
* namespace: This is the namespace where the module is located on Door43, in the format: <lang>/ta/<volume>/<section>/<slug>
  * slug (derived): the short name of the module (also the filename on Door43 filesystem)
  * section (derived): the section of tA in which the module belongs (one of four: intro, translate, check, tech)
  * volume (derived): which volume the module is in (one of two: vol1, vol2)
* dependencies: A list of prerequisite modules, e.g. "intro", "howdy"
* status: The status of the module, one of: needed, drafting, drafted, reviewed, finished

YAML example:
```
---
title: Why do we do what we do?
namespace: en/ta/vol1/intro/why
dependencies: "intro", "howdy"
status: drafted
---
```
notes:
* the derived slug is “why"
* the derived section is “intro"
* the derived volume is “vol1"

links:

root page: https://pad.door43.org/p/ta-modules
test pages: 
https://pad.door43.org/p/testmod1
https://pad.door43.org/p/testmod2
https://pad.door43.org/p/testmod3

next steps:

— create a script that process each module
— retrieves the content for each of the test modules (linked above)
— processes the YAML headers of each
— writes the content of the module in the correct page on Door43
— creates a Graphviz diagram of the dependencies between the modules

**Comment by jag3773** [comment]
The https://github.com/Door43/tools/blob/master/uwb/ep_chunk.py script has an example of doing something similar.

**Comment by phillip-hopper** [comment]
@jag3773 , what is tA?

**Comment by jag3773** [comment]
Translation academy

**Comment by jag3773** [comment]
Put graphviz in https://door43.org/en/ta/dependencies.

**Comment by jag3773** [comment]
Put tA as the top level in the graph, should be built from the bottom up.  Color code Introduction, Checking, Technology, Translation sections uniquely (take your pick for now).

The YAML and content pages have changed slightly, example:
```
---
title: Why we translate the Bible
question: Why should we translate the Bible?
manual: translate
volume: 1
slug: why_translate
dependencies: 
status: draft
---

This is the content part, the answer to the question above.
```

The "slug" field is unique *across all of tA*.

**Comment by phillip-hopper** [comment]
@jag3773 , @timdsm , Just a yaml note - an array needs to be inside square brackets. The page https://pad.door43.org/p/ta-vol1-intro-why has dependencies listed like this:

`dependencies: "intro", "howdy"`

which doesn't parse correctly. it should be:

`dependencies: ["intro", "howdy"]`

**Comment by timdsm** [comment]
Thanks, Phil. We will adjust accordingly.

**Comment by phillip-hopper** [comment]
Finished. If there are problems, it would be better to create a new issue rather than to reopen this one.
