### ISSUE TITLE
Import CC Licensing

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/tools#38]
It looks like the bit starting https://github.com/Door43/tools/blob/master/general_tools/ccsa_import/import_ccsa_licenses.py#L181 is going to do a gi tpush in the wrong location.  Every namespace has it's own repository, so we should be doing a git commit & push with a cwd of something like data/gitrepo/pages/$langcode .  Does that make sense?

**Comment by phillip-hopper** [comment]
@jag3773, yes it does.

**Comment by jag3773** [comment]
So what is next here, is that script safe to run, does it still need to be run or are we doing something different here now?

**Comment by jag3773** [comment]
This issue was moved to unfoldingWord-dev/Door43#296
