### ISSUE TITLE
tA(d43) to epad to tA(d43)

### ISSUE THREAD

**Issue by ChrisJarka** [unfoldingWord-dev/tools#59]
There are some unexpected results in the final door43 pages. See the attached screen captures of the original page, code of the original page, epad page and the final page outcome.
Why is this happening? Or should I not be concerned with the outcome? 
What needs to be done to correct this?
Should we make sure that all returns are coded in?

![epad terms page](https://cloud.githubusercontent.com/assets/9850185/8288460/4c17660c-18e4-11e5-8a3f-100b6f947f5b.png)
![original dk code](https://cloud.githubusercontent.com/assets/9850185/8288459/4c174cda-18e4-11e5-9eea-798617747e48.png)
![terms original page](https://cloud.githubusercontent.com/assets/9850185/8288458/4c1682c8-18e4-11e5-95a1-183179770edb.png)
![vol1 terms page](https://cloud.githubusercontent.com/assets/9850185/8288457/4c15af60-18e4-11e5-8898-9efb05a92a81.png)

**Comment by phillip-hopper** [comment]
@ChrisJarka, I think you need to insert a blank line to start a new paragraph, let me check.

**Comment by ChrisJarka** [comment]
Phil,
There is a line between each paragraph….
**Form** - the words, language, grammar, illustrations, idioms, word order, and any other features that are used in the text.

**Meaning** - the underlying idea or concept that the text is trying to communicate to the reader.

**Source Language** - the language //from// which the translation is being made.

Blessings,
Christine
407-852-5343

**Comment by phillip-hopper** [comment]
@ChrisJarka Sorry for the confusion. I put the blank lines in. If you look at the blue highlighted section near the top of the image you attached, you can see the original state, there were no blank lines. After I inserted the blank lines, the page is being generated correctly, https://door43.org/en/ta/vol1/translate/translate_terms
