### ISSUE TITLE
YAML information not showing on new tA pages

### ISSUE THREAD

**Issue by ChrisJarka** [unfoldingWord-dev/tools#60]
Are the question, dependencies and recommended pages as noted in the YAML on the either pad pages suppose to show on the new generated pages?
On the epad page https://door43.org/en/ta/vol1/translate/translate_what  is this YAML:
--- 
title: What to Start Translating
question: What do I start translating?
manual: translate
volume: 1
slug: translate_what
dependencies:   ["translate_manual"]
status: Review
tags: 
recommended:  ["translate_help", "translate_whatis"]
original url: https://door43.org/en/ta/translate/basics
credits: 
---
The question, dependencies and recommended do not show on the auto generated page: https://door43.org/en/ta/vol1/translate/translate_what

**Comment by phillip-hopper** [comment]
@ChrisJarka I don't have any information that tells me those fields are used. What should be done with them?

**Comment by jag3773** [comment]
@ChrisJarka The question here is "How do you want that information displayed?"  I don't think we documented that anywhere, so now would be the time!

**Comment by ChrisJarka** [comment]
Jesse and Phil, I don't know. I was blindly following instructions from our Tuesday night meetings. I thought that the recommendations would show as links on the "b" page, the question would also be on the "b" page and the "a" pages that were dependencies in the "b" page's YAML would have links from them to the "b" page.
I thought this was all being done for the tA app.
I'm having a meeting with Ben tomorrow, maybe he can answer this question.

**Comment by phillip-hopper** [comment]
@ChrisJarka Regarding this issue, you should assume if you didn't tell me yourself, I don't know it.

**Comment by ChrisJarka** [comment]
@phillip-hopper I'll let you know when I know.
\

**Comment by ChrisJarka** [comment]
We would like to see the import process of tA include the following for each module: 

- - - -
[Title]
This module answers the question: [Question]
Before you start this module have you learned about: [Dependencies]?

[content of the module]

Next we recommend you learn about: [Recommended].
- - - - 
Is this possible?

**Comment by phillip-hopper** [comment]
@ChrisJarka  Yes, that's what I need. Thank-you.

**Comment by phillip-hopper** [comment]
@ChrisJarka I have started on this. You may notice some changes in the generated files, but I still have work to do.

**Comment by phillip-hopper** [comment]
Finished.
