### ISSUE TITLE
Update links in the new Translation Academy documents.

### ISSUE THREAD

**Issue by phillip-hopper** [unfoldingWord-dev/tools#67]
From Ben Jore: In the YAML data, each page has the url of the “original” page. Is it possible to run a script on the export that searches for links to the “original” page and update it to the slug for the new page? In this example, https://door43.org/en/ta/vol1/intro/translation_guidelines, the link is “en:ta:translate:accurate” could that be update via script to go to “en:ta:vol1:translate:guidelines_accurate”? Both are found in the YAML data of each page.

**Comment by ChrisJarka** [comment]
On this page, the links in the dependency and recommended are correct but the inline links in the content are still going to the original pages - see the links in the content on https://door43.org/en/ta/vol1/intro/translation_guidelines

**Comment by phillip-hopper** [comment]
@ChrisJarka, @benjore -- is this still a problem, or can this issue be closed?

**Comment by ChrisJarka** [comment]
This can be closed - the corrections were done manually
