### ISSUE TITLE
New Versioning System

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/tools#83]
We need to implement the new versioning system, explained in detail in https://pad.door43.org/p/2015-06-proposed_versioning_system.

**Comment by jag3773** [comment]
Expected roll out date for this is first part of August.

**Comment by alerque** [comment]
Can we get the current version (and checking level) being returned in the json data for each data set coming out of the api? Implementing the version tag in the outputers is easy if we had the data to work with. Does this need to be an issue on some other repo?

**Comment by jag3773** [comment]
@alerque For OBS, this returns the version: https://github.com/unfoldingWord-dev/tools/blob/master/uw/get_ver.py .

Closign this as it has been folded into https://github.com/unfoldingWord-dev/uwadmin/issues/39.
