### ISSUE TITLE
Language properties not set

### ISSUE THREAD

**Issue by alerque** [unfoldingWord-dev/tools#87]
The OBS - PDF output (even after the stuff in #86 gets merged) does not tag the content so that ConTeXt actually knows what it's typesetting. As a result it ends up doing some things wrong. One example is that hyphenation is being done based on English language rules, but in, for example, Turkish, that breaks words on the wrong boundaries.

This will also be an even bigger problem for accessibility tools like screen readers as the output isn't tagged right and also for complex script languages that need more clues about where to typeset content that just starting at the top left.

The correct per-language packages and settings need to be loaded and the body content correctly tagged (possibly differently than the front/back matter).

**Comment by jag3773** [comment]
This issue was moved to unfoldingWord-dev/Door43#290
