### ISSUE TITLE
Layout images in OBS PDFs to page grid

### ISSUE THREAD

**Issue by alerque** [unfoldingWord-dev/tools#88]
As is typical with Bible printings where typesetting must be done on a vertical grid to avoid bleed-through on thin paper making lines hard to read, so the images in the 2up PDF output should be lined up between front and back pages (or in this case all the way through the document). The images being offset one way or another produces some pretty serious bleed through when printed on cheap paper.

**Comment by jag3773** [comment]
This issue was moved to unfoldingWord-dev/Door43#289
