### ISSUE TITLE
Merge OBS PDF build scripts

### ISSUE THREAD

**Issue by alerque** [unfoldingWord-dev/tools#89]
As mentioned in #86, the combination of `build_all_DPB.sh` and `obs/book/publish_PDF.sh` is clumsy and usage is a bit obtuse. Even though it works, these should probably be merged and the various options and variables combined so that they work for all use cases:

* One-off runs of a single language for anybody that clones the repo
* Batch runs to regenerate the latest of everything
* Hooks or API callbacks that trigger builds of specific resources and put them in predefined places

**Comment by alerque** [comment]
I started work on this [in this branch](https://github.com/alerque/tools/commits/merge-scripts) but won't have time (or be at a computer) to finish it until Friday morning at the earliest.

**Comment by jag3773** [comment]
By the way, CLI flags are far preferable to environment variables.

**Comment by alerque** [comment]
@jag3773 I realize that, but its a lot easier to prototype and debug shell code that expects vars because you can stop and start it from anywhere as you go. I left the mix and match mess only because I was out of time and already had a merge of the two scripts in mind.

**Comment by jag3773** [comment]
Is this taken care of now?
