### ISSUE TITLE
tN PDF: Pandoc Issues

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/tools#99]
Fix pandoc to support images, or fix pandoc-dev list spacing.  Possibly just install 1.15 from https://github.com/jgm/pandoc/releases.

**Comment by greenpotatochip** [comment]
installed pandoc 1.15 on test.door43.org and 2015 texlive in /usr/local/texlive/2015/bin/x86_64-linux
added 
pathmunge /usr/local/texlive/2015/bin/x86_64-linux
to /etc/profile

**Comment by jag3773** [comment]
If this is working correctly then we'll want to update the puppet recipe to do what you have done here.

**Comment by greenpotatochip** [comment]
The only reports I have so far is that it's working, and seems to be working better than the one on prod. I'm not sure if it fixed whatever issue prompted the update to begin with though? I hope to get some puppet updates done this weekend.

**Comment by phillip-hopper** [comment]
My experience is that Pandoc 1.15 will include images from URL's, but 1.12 only would include images using the local file system.

**Comment by richmahn** [comment]
So, should I try removing the code in the shell script that strips out the image tags and see if it works?

**Comment by richmahn** [comment]
What else does this fix? I don't know what the "ulem" issue is...does it deal with this upgrade?

**Comment by phillip-hopper** [comment]
The markdown format for embedded images starts with an exclamation mark, 
```
![description goes here](https://door43.org/_media/some/location/imagename.png)
```

**Comment by greenpotatochip** [comment]
pandoc and texlive have been upgraded on us.door43.org (prod).
The full install of texlive says it included ulem, so that issue may be solved too. 
They should be in your path. Please let me know of any issues.

**Comment by greenpotatochip** [comment]
Notes on Pandoc / Texlive install 
```
------ pandoc install -------

1. sudo yum install haskell-platform
2. As a normal user with sudo priv, run
	cabal update
   The scripts invoke sudo when they need it 
3. Then edit ~/.cabal/config file (a default file should exist there)	
   Note "--" is a comment in this file
   The three lines that are modified from the default are:
	user-install: False
	root-cmd: sudo
	prefix: /usr/local  (under the GLOBAL SECTION)
4. As the same normal user, run
   	cabal install pandoc pandoc-citeproc --dry-run -v    (this tests the config)
   If that looks good, run it w/o the "--dry-run -v"
	cabal install pandoc pandoc-citeproc

And then wait while it builds and installs everything. This generates
many many warnings. It should put pandoc in /usr/local/bin/

######### texlive install ###############

followed this: http://www.tug.org/texlive/quickinstall.html
using this source: http://www.tug.org/texlive/acquire-netinstall.html

wget http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz
tar xvfz install-tl-unx.tar.gz 
cd install-tl-20150724/
sudo ./install-tl (installs 4+GB of files)
(this has a ncurses menu for configuration options )

# add this to /etc/profile
pathmunge /usr/local/texlive/2015/bin/x86_64-linux
```

**Comment by dsm-git** [comment]
Please add a wiki page for this in the Door43 repo.

**Comment by greenpotatochip** [comment]
Can you point me to a link to do that?

**Comment by phillip-hopper** [comment]
@greenpotatochip: https://github.com/unfoldingWord-dev/Door43/wiki

**Comment by jag3773** [comment]
This issue was moved to unfoldingWord-dev/sysadmin#28
